matrix:
  include:
    - language: ruby
      rvm: 2.2
      brfore_script: 
        - gem install awesome_bot
      script:
        - awesome_bot README.md --allow-ssl --allow-dupe --allow-redirect --base-url "$TRAVIS_BUILD_DIR"

    - language: objective-c
      osx_image: xcode10.1
      xcode_project: FFPopup.xcodeproj
      xcode_scheme: FFPopup
      before_install:
        - env
        - xcodebuild -version
        - xcodebuild -showsdks
        - xcpretty --version
      script:
        - set -o pipefail
        - xcodebuild clean build -project "$TRAVIS_XCODE_PROJECT"  -scheme "$TRAVIS_XCODE_SCHEME" | xcpretty

notifications:
  email:
    - jony.chunfang@gmail.com
